html:
  - content:
      name: js
      type: folder
      path: "/js"

  - content:
      name: custome.js
      type: file
      path: "/js/custome.js"
      data: "yoy can put your js code at here\n testing new line"


angular:
  - content:
      name: js
      type: folder
      path: "/js"

  - content:
      name: common.js
      type: file
      path: "/js/common.js"
      data: "yoy can put your js code at here"
